-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');

-- CreateEnum
CREATE TYPE "VolunteerRole" AS ENUM ('MEMBER', 'LEADER', 'MANAGER');

-- CreateEnum
CREATE TYPE "EventStatus" AS ENUM ('UPCOMING', 'ONGOING', 'FINISHED', 'CANCELED');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('SYSTEM', 'EVENT', 'ORGANIZATION');

-- CreateEnum
CREATE TYPE "OrganizationType" AS ENUM ('NGO', 'GOVERNMENT', 'COMPANY', 'SCHOOL', 'OTHER');

-- CreateTable
CREATE TABLE "COUNTRY" (
    "ID_COUNTRY" SERIAL NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "COUNTRY_pkey" PRIMARY KEY ("ID_COUNTRY")
);

-- CreateTable
CREATE TABLE "VOLUNTEER" (
    "ID_USER" SERIAL NOT NULL,
    "ID_COUNTRY" INTEGER NOT NULL,
    "FULLNAME" TEXT,
    "EMAIL" TEXT,
    "PHONE" TEXT,
    "PASSWORD" TEXT,
    "AVATAR" TEXT,
    "GENDER" "Gender",
    "DATEOFBIRTH" TIMESTAMP(3),
    "ADDRESS" TEXT,
    "BIO" TEXT,
    "ROLE" "VolunteerRole",
    "ISACTIVE" BOOLEAN,
    "REFRESHTOKEN" TEXT,
    "EMAILVERIFIED" BOOLEAN,
    "LASTLOGIN" TIMESTAMP(3),
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VOLUNTEER_pkey" PRIMARY KEY ("ID_USER")
);

-- CreateTable
CREATE TABLE "ORGANIZATION" (
    "ID_ORGANIZATION" SERIAL NOT NULL,
    "NAME" TEXT,
    "TYPE" "OrganizationType",

    CONSTRAINT "ORGANIZATION_pkey" PRIMARY KEY ("ID_ORGANIZATION")
);

-- CreateTable
CREATE TABLE "EVENT" (
    "ID_EVENT" SERIAL NOT NULL,
    "ID_ORGANIZATION" INTEGER NOT NULL,
    "ID_HAMLET" INTEGER NOT NULL,
    "TITLE" TEXT,
    "DESCRIPTION" TEXT,
    "IMAGE" TEXT,
    "MAXVOLUNTEERS" INTEGER NOT NULL DEFAULT 0,
    "CURRENTPARTICIPANTS" INTEGER NOT NULL DEFAULT 0,
    "ADDRESS" TEXT,
    "STARTDATE" TIMESTAMP(3),
    "ENDDATE" TIMESTAMP(3),
    "STATUS" "EventStatus",
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EVENT_pkey" PRIMARY KEY ("ID_EVENT")
);

-- CreateTable
CREATE TABLE "SKILL" (
    "ID_SKILL" SERIAL NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "SKILL_pkey" PRIMARY KEY ("ID_SKILL")
);

-- CreateTable
CREATE TABLE "USERSKILL" (
    "ID_USER" INTEGER NOT NULL,
    "ID_SKILL" INTEGER NOT NULL,

    CONSTRAINT "USERSKILL_pkey" PRIMARY KEY ("ID_USER","ID_SKILL")
);

-- CreateTable
CREATE TABLE "EVENTSKILL" (
    "ID_EVENT" INTEGER NOT NULL,
    "ID_SKILL" INTEGER NOT NULL,

    CONSTRAINT "EVENTSKILL_pkey" PRIMARY KEY ("ID_EVENT","ID_SKILL")
);

-- CreateTable
CREATE TABLE "LIST_OF_SUPPORT_TASKS" (
    "ID_LIST" SERIAL NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "LIST_OF_SUPPORT_TASKS_pkey" PRIMARY KEY ("ID_LIST")
);

-- CreateTable
CREATE TABLE "SUPPORTFORVOLUNTEERS" (
    "ID_LIST" INTEGER NOT NULL,
    "ID_USER" INTEGER NOT NULL,
    "STARTDATE" TIMESTAMP(3),
    "ENDDATE" TIMESTAMP(3),
    "NOTE" TEXT,

    CONSTRAINT "SUPPORTFORVOLUNTEERS_pkey" PRIMARY KEY ("ID_LIST","ID_USER")
);

-- CreateTable
CREATE TABLE "PARTICIPATION" (
    "ID_USER" INTEGER NOT NULL,
    "ID_ORGANIZATION" INTEGER NOT NULL,
    "STARTDATE" TIMESTAMP(3),
    "ENDDATE" TIMESTAMP(3),

    CONSTRAINT "PARTICIPATION_pkey" PRIMARY KEY ("ID_USER","ID_ORGANIZATION")
);

-- CreateTable
CREATE TABLE "JOIN" (
    "ID_USER" INTEGER NOT NULL,
    "ID_EVENT" INTEGER NOT NULL,
    "STARTDATE" TIMESTAMP(3),
    "ENDDATE" TIMESTAMP(3),
    "DESCRIPTION" TEXT,

    CONSTRAINT "JOIN_pkey" PRIMARY KEY ("ID_USER","ID_EVENT")
);

-- CreateTable
CREATE TABLE "NOTIFICATION" (
    "ID_NOTIFICATION" SERIAL NOT NULL,
    "ID_EVENT" INTEGER NOT NULL,
    "TITLE" TEXT,
    "CONTENT" TEXT,
    "TYPE" "NotificationType",
    "CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NOTIFICATION_pkey" PRIMARY KEY ("ID_NOTIFICATION")
);

-- CreateTable
CREATE TABLE "NOTIFICATION_USER" (
    "ID_USER" INTEGER NOT NULL,
    "ID_NOTIFICATION" INTEGER NOT NULL,
    "ISREAD" BOOLEAN,

    CONSTRAINT "NOTIFICATION_USER_pkey" PRIMARY KEY ("ID_USER","ID_NOTIFICATION")
);

-- CreateTable
CREATE TABLE "PROVINCE" (
    "ID_PROVINCE" SERIAL NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "PROVINCE_pkey" PRIMARY KEY ("ID_PROVINCE")
);

-- CreateTable
CREATE TABLE "COMMUNE" (
    "ID_COMMUNE" SERIAL NOT NULL,
    "ID_PROVINCE" INTEGER NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "COMMUNE_pkey" PRIMARY KEY ("ID_COMMUNE")
);

-- CreateTable
CREATE TABLE "HAMLET" (
    "ID_HAMLET" SERIAL NOT NULL,
    "ID_COMMUNE" INTEGER NOT NULL,
    "NAME" TEXT,

    CONSTRAINT "HAMLET_pkey" PRIMARY KEY ("ID_HAMLET")
);

-- CreateTable
CREATE TABLE "LOCATION_USER" (
    "ID_HAMLET" INTEGER NOT NULL,
    "ID_USER" INTEGER NOT NULL,

    CONSTRAINT "LOCATION_USER_pkey" PRIMARY KEY ("ID_HAMLET","ID_USER")
);

-- CreateIndex
CREATE UNIQUE INDEX "COUNTRY_NAME_key" ON "COUNTRY"("NAME");

-- CreateIndex
CREATE UNIQUE INDEX "VOLUNTEER_EMAIL_key" ON "VOLUNTEER"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "VOLUNTEER_PHONE_key" ON "VOLUNTEER"("PHONE");

-- CreateIndex
CREATE INDEX "VOLUNTEER_EMAIL_idx" ON "VOLUNTEER"("EMAIL");

-- CreateIndex
CREATE INDEX "VOLUNTEER_PHONE_idx" ON "VOLUNTEER"("PHONE");

-- CreateIndex
CREATE INDEX "VOLUNTEER_ID_COUNTRY_idx" ON "VOLUNTEER"("ID_COUNTRY");

-- CreateIndex
CREATE UNIQUE INDEX "ORGANIZATION_NAME_key" ON "ORGANIZATION"("NAME");

-- CreateIndex
CREATE INDEX "EVENT_ID_ORGANIZATION_idx" ON "EVENT"("ID_ORGANIZATION");

-- CreateIndex
CREATE INDEX "EVENT_ID_HAMLET_idx" ON "EVENT"("ID_HAMLET");

-- CreateIndex
CREATE INDEX "EVENT_STATUS_idx" ON "EVENT"("STATUS");

-- CreateIndex
CREATE UNIQUE INDEX "SKILL_NAME_key" ON "SKILL"("NAME");

-- CreateIndex
CREATE INDEX "USERSKILL_ID_SKILL_idx" ON "USERSKILL"("ID_SKILL");

-- CreateIndex
CREATE INDEX "EVENTSKILL_ID_SKILL_idx" ON "EVENTSKILL"("ID_SKILL");

-- CreateIndex
CREATE UNIQUE INDEX "LIST_OF_SUPPORT_TASKS_NAME_key" ON "LIST_OF_SUPPORT_TASKS"("NAME");

-- CreateIndex
CREATE INDEX "SUPPORTFORVOLUNTEERS_ID_USER_idx" ON "SUPPORTFORVOLUNTEERS"("ID_USER");

-- CreateIndex
CREATE INDEX "PARTICIPATION_ID_ORGANIZATION_idx" ON "PARTICIPATION"("ID_ORGANIZATION");

-- CreateIndex
CREATE INDEX "JOIN_ID_EVENT_idx" ON "JOIN"("ID_EVENT");

-- CreateIndex
CREATE INDEX "NOTIFICATION_ID_EVENT_idx" ON "NOTIFICATION"("ID_EVENT");

-- CreateIndex
CREATE INDEX "NOTIFICATION_USER_ID_NOTIFICATION_idx" ON "NOTIFICATION_USER"("ID_NOTIFICATION");

-- CreateIndex
CREATE UNIQUE INDEX "PROVINCE_NAME_key" ON "PROVINCE"("NAME");

-- CreateIndex
CREATE INDEX "COMMUNE_ID_PROVINCE_idx" ON "COMMUNE"("ID_PROVINCE");

-- CreateIndex
CREATE UNIQUE INDEX "COMMUNE_ID_PROVINCE_NAME_key" ON "COMMUNE"("ID_PROVINCE", "NAME");

-- CreateIndex
CREATE INDEX "HAMLET_ID_COMMUNE_idx" ON "HAMLET"("ID_COMMUNE");

-- CreateIndex
CREATE UNIQUE INDEX "HAMLET_ID_COMMUNE_NAME_key" ON "HAMLET"("ID_COMMUNE", "NAME");

-- CreateIndex
CREATE INDEX "LOCATION_USER_ID_USER_idx" ON "LOCATION_USER"("ID_USER");

-- AddForeignKey
ALTER TABLE "VOLUNTEER" ADD CONSTRAINT "VOLUNTEER_ID_COUNTRY_fkey" FOREIGN KEY ("ID_COUNTRY") REFERENCES "COUNTRY"("ID_COUNTRY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT" ADD CONSTRAINT "EVENT_ID_ORGANIZATION_fkey" FOREIGN KEY ("ID_ORGANIZATION") REFERENCES "ORGANIZATION"("ID_ORGANIZATION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT" ADD CONSTRAINT "EVENT_ID_HAMLET_fkey" FOREIGN KEY ("ID_HAMLET") REFERENCES "HAMLET"("ID_HAMLET") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERSKILL" ADD CONSTRAINT "USERSKILL_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERSKILL" ADD CONSTRAINT "USERSKILL_ID_SKILL_fkey" FOREIGN KEY ("ID_SKILL") REFERENCES "SKILL"("ID_SKILL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTSKILL" ADD CONSTRAINT "EVENTSKILL_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "EVENT"("ID_EVENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTSKILL" ADD CONSTRAINT "EVENTSKILL_ID_SKILL_fkey" FOREIGN KEY ("ID_SKILL") REFERENCES "SKILL"("ID_SKILL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUPPORTFORVOLUNTEERS" ADD CONSTRAINT "SUPPORTFORVOLUNTEERS_ID_LIST_fkey" FOREIGN KEY ("ID_LIST") REFERENCES "LIST_OF_SUPPORT_TASKS"("ID_LIST") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUPPORTFORVOLUNTEERS" ADD CONSTRAINT "SUPPORTFORVOLUNTEERS_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPATION" ADD CONSTRAINT "PARTICIPATION_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPATION" ADD CONSTRAINT "PARTICIPATION_ID_ORGANIZATION_fkey" FOREIGN KEY ("ID_ORGANIZATION") REFERENCES "ORGANIZATION"("ID_ORGANIZATION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JOIN" ADD CONSTRAINT "JOIN_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JOIN" ADD CONSTRAINT "JOIN_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "EVENT"("ID_EVENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "EVENT"("ID_EVENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION_USER" ADD CONSTRAINT "NOTIFICATION_USER_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION_USER" ADD CONSTRAINT "NOTIFICATION_USER_ID_NOTIFICATION_fkey" FOREIGN KEY ("ID_NOTIFICATION") REFERENCES "NOTIFICATION"("ID_NOTIFICATION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMMUNE" ADD CONSTRAINT "COMMUNE_ID_PROVINCE_fkey" FOREIGN KEY ("ID_PROVINCE") REFERENCES "PROVINCE"("ID_PROVINCE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HAMLET" ADD CONSTRAINT "HAMLET_ID_COMMUNE_fkey" FOREIGN KEY ("ID_COMMUNE") REFERENCES "COMMUNE"("ID_COMMUNE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOCATION_USER" ADD CONSTRAINT "LOCATION_USER_ID_HAMLET_fkey" FOREIGN KEY ("ID_HAMLET") REFERENCES "HAMLET"("ID_HAMLET") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOCATION_USER" ADD CONSTRAINT "LOCATION_USER_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "VOLUNTEER"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;
